version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: build dependencies
          command: bundle install

      - run:
          name: build the jekyll site
          command: REPLACE-ME-WITH-BUILD-COMMAND

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
